package javaUI;


import .*;
import Project.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dwive
 */
public class DELETE_DOCTOR_NURSE extends javax.swing.JFrame {

    /**
     * Creates new form DELETE_DOCTOR_NURSE
     */
    public DELETE_DOCTOR_NURSE() {
        initComponents();
        jLabel14.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField6.setVisible(false);
        jTextField10.setVisible(false);
        jButton2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel6.setVisible(false);
        jLabel3.setVisible(false);
        jLabel8.setVisible(false);
        jLabel13.setVisible(false);
        jLabel15.setVisible(false);
        jTextField4.setVisible(false);
        jLabel5.setVisible(false);      
        jTextField11.setVisible(false);       
        jTextField12.setVisible(false);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel60 = new javax.swing.JLabel();
        jTextField53 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jTextField54 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField39 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTextField40 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jTextField41 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jTextField51 = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jTextField52 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Enter Staff ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 210, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 90, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("Record Not Found!!");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("First Name*");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 200, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Last Name*");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 200, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Email ID*");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 200, 25));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Phone Number*");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jTextField11.setEditable(false);
        jTextField11.setText("+49");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 50, 25));

        jTextField12.setEditable(false);
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 210, 25));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back small.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 37, 39));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Gender");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 80, 25));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel60.setText("Qualification");
        getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        jTextField53.setEditable(false);
        jTextField53.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField53.setPreferredSize(new java.awt.Dimension(25, 25));
        jTextField53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField53ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField53, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 200, 25));

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel61.setText("Specialization");
        getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 20));

        jTextField54.setEditable(false);
        jTextField54.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField54.setPreferredSize(new java.awt.Dimension(25, 25));
        jTextField54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField54ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField54, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 200, 25));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("House Number");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, 20));

        jTextField39.setEditable(false);
        jTextField39.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField39.setPreferredSize(new java.awt.Dimension(25, 25));
        jTextField39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField39ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 200, 25));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Street Name");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, 20));

        jTextField35.setEditable(false);
        jTextField35.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField35.setPreferredSize(new java.awt.Dimension(25, 25));
        jTextField35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField35ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 200, 25));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setText("City");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, 20));

        jTextField40.setEditable(false);
        jTextField40.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField40.setPreferredSize(new java.awt.Dimension(25, 25));
        jTextField40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField40ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 200, 25));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setText("Zip Code");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, 20));

        jTextField41.setEditable(false);
        jTextField41.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField41.setPreferredSize(new java.awt.Dimension(25, 25));
        jTextField41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField41ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField41, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 200, 25));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setText("State");
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, 20));

        jTextField51.setEditable(false);
        jTextField51.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField51.setPreferredSize(new java.awt.Dimension(25, 25));
        jTextField51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField51ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField51, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 200, 25));

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel59.setText("Country");
        getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, 20));

        jTextField52.setEditable(false);
        jTextField52.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTextField52.setPreferredSize(new java.awt.Dimension(25, 25));
        jTextField52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField52ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField52, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 200, 25));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //Search Doctor/Nurse
        String ID = jTextField1.getText();
        try
        {
            //Call connection
            Connection con = ConnectionProvider.getCon();
            Statement stm = con.createStatement();
            if(jRadioButton1.isSelected())
            {
                ResultSet rsd = stm.executeQuery("select d_firstname, d_lastname, country_code, contact_number, d_email, address, patient_quota "
                    + "from doctor_details where doctor_id = '"+ID+"'");
                if(rsd.next())
                {//Make fields visible
                    jTextField2.setVisible(true);
                    jTextField3.setVisible(true);
                    jTextField6.setVisible(true);
                    jTextField10.setVisible(true);
                    jButton2.setVisible(true);
                    jLabel3.setVisible(true);
                    jLabel4.setVisible(true);
                    jLabel6.setVisible(true);
                    jLabel3.setVisible(true);
                    jLabel8.setVisible(true);
                    jLabel13.setVisible(true);
                    jLabel15.setVisible(true);
                    jTextField4.setVisible(true);
                    jLabel5.setVisible(true);
                    jTextField11.setVisible(true);
                    jTextField12.setVisible(true);
                    //Set values to fields
                    jTextField2.setText(rsd.getString(1));
                    jTextField3.setText(rsd.getString(2));
                    jTextField6.setText(rsd.getString(5));
                    jTextField10.setText(rsd.getString(7));

                    jTextField4.setText(rsd.getString(6));
                    jTextField11.setText(rsd.getString(3));
                    jTextField12.setText(rsd.getString(4));

                }
                else
                {
                    jLabel14.setVisible(true);
                }
            }
            else
            {
                ResultSet rsn = stm.executeQuery("select n_firstname, n_lastname, country_code, contact_number, n_email, address, patient_quota "
                    + "from nurse_details where nurse_id = '"+ID+"'");
                if(rsn.next())
                {//Make fields visible
                    jTextField2.setVisible(true);
                    jTextField3.setVisible(true);
                    jTextField6.setVisible(true);
                    jTextField10.setVisible(true);
                    jButton2.setVisible(true);
                    jLabel3.setVisible(true);
                    jLabel4.setVisible(true);
                    jLabel6.setVisible(true);
                    jLabel3.setVisible(true);
                    jLabel8.setVisible(true);
                    jLabel13.setVisible(true);
                    jLabel15.setVisible(true);
                    jTextField4.setVisible(true);
                    jLabel5.setVisible(true);
                    jTextField11.setVisible(true);
                    jTextField12.setVisible(true);
                    //Set values to fields
                    jTextField2.setText(rsn.getString(1));
                    jTextField3.setText(rsn.getString(2));
                    jTextField6.setText(rsn.getString(5));
                    jTextField10.setText(rsn.getString(7));

                    jTextField4.setText(rsn.getString(6));
                    jTextField11.setText(rsn.getString(3));
                    jTextField12.setText(rsn.getString(4));

                }
                else
                {
                    jLabel14.setVisible(true);
                }
            }
        }catch(Exception e)
        {JOptionPane.showMessageDialog(null, e.getMessage());}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //Update doctor/Nurse to hospital
        String ID = jTextField1.getText();
        int d_id = Integer.parseInt(ID);
         try{
                if(jRadioButton1.isSelected())
                {
                    ///Call connection
                Connection con = ConnectionProvider.getCon();
                Statement stm = con.createStatement();
                //Delete doctor
                stm.executeUpdate("delete from doctor_details where doctor_id = '"+d_id+"'");
                JOptionPane.showMessageDialog(null, "Deleted Successfully!!");
                setVisible(false);
                    new DELETE_DOCTOR_NURSE().setVisible(true);
                }else
                {
                    ///Call connection
                Connection con = ConnectionProvider.getCon();
                Statement stm = con.createStatement();
                //Delete nurse
                stm.executeUpdate("delete from nurse_details where nurse_id = '"+d_id+"'");
                JOptionPane.showMessageDialog(null, "Deleted Successfully!!");
                setVisible(false);
                    new DELETE_DOCTOR_NURSE().setVisible(true);
                }
            }
            catch(Exception e)
            {JOptionPane.showMessageDialog(null, e.getMessage());}
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new MAINSCREEN().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField53ActionPerformed

    private void jTextField54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField54ActionPerformed

    private void jTextField39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField39ActionPerformed

    private void jTextField35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField35ActionPerformed

    private void jTextField40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField40ActionPerformed

    private void jTextField41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField41ActionPerformed

    private void jTextField51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField51ActionPerformed

    private void jTextField52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField52ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DELETE_DOCTOR_NURSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DELETE_DOCTOR_NURSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DELETE_DOCTOR_NURSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DELETE_DOCTOR_NURSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DELETE_DOCTOR_NURSE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
